Iter9
Gamilkarr/stattrack pull request #11
Opened 2024-02-09 15:30 UTC by Gamilkarr

2024-02-09 18:48 UTC, Nikscorp requested changes
Привет!

К сожалению замечаний много, аппрув поставить пока не могу.
Замечания оставил в комментариях к PR.
При исправлении — просьба в них отписываться и потом не забыть их запаблишить.

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +	"net/http"
не сортируются import-ы. Настрой использование goimports в своей IDE при сохранении файла

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +		log.WithField("fatal error", uploading(cfg.FileStoragePath, repo))
а тут почему fatal error? Ты же здесь и не логируешь ничего

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +func backUP(path string, period time.Duration, repo *repository.MemStorage) {
все что ниже точно не должно лежать в cmd. А должно инкапсулироваться в Storage слое

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +func NewRouter(h *handlers.Handler) *chi.Mux {
роутеру тоже не место в cmd, его лучше в слой с хэндлерами

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +	log.WithField("fatal error", http.ListenAndServe(cfg.Address, logger.WithLogging(compress.GzipMiddleware(NewRouter(h))))).Fatal()
а здесь то почему fatal? Логировать с фаталом нужно только если пришла ошибка, а тебя получается априори приложение завершится с ненулевым кодом

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +		log.WithField("backup error", err)
эта строка по сути ничего не делает (и даже не логирует), более того твой флоу идет дальше и при ошибке ты получишь панику

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +		if err != nil {
а тут зачем проверять ошибку? Мы же ее уже проверили

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +	defer file.Close()
а вот ошибку закрытия write-файла стоит обрабатывать

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +			log.WithField("backup error", err)
эта строка аналогично ничего не делает

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +			log.WithField("backup error", err)
и эта

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +		return err
ошибки, которые ты возвращаешь, почти всегда стоит wrapp-ать.
https://github.com/uber-go/guide/blob/master/style.md#error-wrapping

2024-02-09 18:48 UTC, Nikscorp commented on configs/agent/flags.go
> +	addr := configs.NetAddress{
зачем разделять адрес на хост и порт? Это имело смысл в си, в go в этом как будто нет смысла, ты же в итоге их снова соединеяешь

2024-02-09 18:48 UTC, Nikscorp commented on configs/server/flags.go
> +	fileStoragePath := flag.String("f", "/Users/takhabarova/learningProjects/stattrack/tmp/metrics-db.json", "path for saving server data to disk")
хардкод абсолютного пути на твоей машине, так делать не стоит

2024-02-09 18:48 UTC, Nikscorp commented on internal/client/client.go
> +		msg, _ := json.Marshal(metric)
многие ошибки игнорируются, в go их игнорировать не следует.

Вообще ошибки здесь стоит прикидывать выше и на самом высоком уровне уже решать что с ними делать — например логировать / или прерывать работу

2024-02-09 18:48 UTC, Nikscorp commented on internal/client/client.go
>  			log.Println(err)
ты получается двумя разными логгерами в своем приложении логируешь

2024-02-09 18:48 UTC, Nikscorp commented on internal/logger/logger.go
> +		log.WithFields(log.Fields{
лучше это делать это в defer-е, чтобы даже в случае паники был лог

2024-02-09 18:48 UTC, Nikscorp commented on internal/logger/logger.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
если вызовется Write без WriteHeader-а — ты залогируешь 0,  а вернешь 200

2024-02-09 18:48 UTC, Nikscorp commented on internal/repository/storage_test.go
> +//import (
так оставлять не стоит — если код не нужен — удали, для доступа к удаленному коду есть git

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +	go backUP(cfg.FileStoragePath, cfg.StoreInterval, repo)
В задании было —

> Флаг -i, переменная окружения STORE_INTERVAL — интервал времени в секундах, по истечении которого текущие показания сервера сохраняются на диск (по умолчанию 300 секунд, значение 0 делает запись синхронной).

то есть пр. StoreInterval == 0, не должна запускаться горутина, а должна происходить запись при каждом обновлении метрик и это запись должна быть блокирующей

2024-02-09 18:48 UTC, Nikscorp commented on cmd/server/main.go
> +		log.WithField("fatal error", err).Fatal()
поле лучше называть просто error / err, а уже в тело сообщения писать о причинах ошибки.

`log.WithField("err", err).Fatal("Failed to create repo")`

2024-02-09 18:48 UTC, Nikscorp commented on configs/server/configs.go
> +	if cfg.StoreInterval == 0 {
в задании не так надо)

2024-04-02 23:21 UTC, Gamilkarr commented on internal/logger/logger.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
Не совсем понимаю в чем проблема, можно подробнее объяснить в чем моя ошибка?

2024-04-13 16:50 UTC, merged